### PR TITLE
🔀🔖 4.1.10

### PR DESCRIPTION
**Pull request by jxn-30**
* 🐛 nl_NL fixed eCW TT translation and vehicles
* ♻️ buildingMarkerAdd triggers API fetch if building not yet registered
* ✨ Add building-list to extensions and buildings at dashboard
* ✨ [mh & ecw] store x & y of overlay
* ✨ [ecw/emv] change text/alert color if selected enough vehicles
* 📝 [de_DE/apps] v3 <=> v4 comparison
* 📝 [docs/de_DE] asyncBtns, chatExtras, clock
* ✨ [ecw/emv & mH] hoverTip setting
* ✨ optional bright tooltips in darkmode
* 🌐 some few translation updates in several languages

### CODE REVIEW

**Review by Ron31 — APPROVED** [review]

**Review by Piet2001 — APPROVED** [review]

**Comment by Suchty112** [comment]
Due to internal releasenote issues currently drafted

**Comment by jxn-30** [comment]
**Releasenotes** will say that `4.1.10` is lower than `4.1.9` because `'4.1.10' < '4.1.9'` evaluates to `true`!

Before merge, we need to update version comparison to compare by integers, and also minor and patch seperately!

**Comment by KokosnussDEV** [comment]
> 
> 
> **Releasenotes** will say that `4.1.10` is lower than `4.1.9` because `'4.1.10' < '4.1.9'` evaluates to `true`!
> 
> Before merge, we need to update version comparison to compare by integers, and also minor and patch seperately!

use the semver npm-pack to check if one version is higher than another ^^

**Comment by jxn-30** [comment]
> > 
> > 
> > **Releasenotes** will say that `4.1.10` is lower than `4.1.9` because `'4.1.10' < '4.1.9'` evaluates to `true`!
> > 
> > Before merge, we need to update version comparison to compare by integers, and also minor and patch seperately!
> 
> use the semver npm-pack to check if one version is higher than another ^^

That was my plan 😉

**Review by Suchty112 — APPROVED** [review]

**Pull request merged**
