### PR TITLE
🔀🚧 Code of Conduct

### LINKED ISSUE #185: [Idea] Code of Conduct
Since the @LSS-Manager team is working with a rather big community of contributors it's time to introduce a Code of Conduct.

### What is a Code of Conduct?
1. A Code of Conduct is a file placed in the projects root folder as `CODE_OF_CONDUCT.md`
2. It's a ["document that establishes expectations for behavior"](https://opensource.guide/code-of-conduct/#why-do-i-need-a-code-of-conduct)
3. It is something all contributors (including admins) should respect and maintain.
Basically, it's a set of rules and [you can read more about what a Code of Conduct is](https://opensource.guide/code-of-conduct/#why-do-i-need-a-code-of-conduct).

Here are 3 examples of very well made Code of Conducts:
The [Django Code of Conduct](https://www.djangoproject.com/conduct/) ([the Enforcement](https://www.djangoproject.com/conduct/enforcement-manual/))
The most used: [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct/)
The one with a good way to report violations: [khmer Code of Conduct](https://github.com/dib-lab/khmer/blob/HEAD/CODE_OF_CONDUCT.rst)

### What should we do with all this information in mind?
We should write our own Code of Conduct or adopt one (or do nothing?) to enforce some basic rules to remind us to respect each of us!

### PR DESCRIPTION
**Pull request by KokosnussDEV**
This PR adds a Code of Conduct as proposed in #185 

What needs to be added:
- [x] 1. @LSS-Manager/developers have to add an e-mail to contact an admin/dev (See https://github.com/LSS-Manager/LSSM-V.4/pull/195#issuecomment-719042500)
- [ ] 2. We should consider a 2nd or 3rd e-mail to contact another person if the report of a violation is related to a team member
  - [ ] A 3rd-party is needed of some kind

This closes #185 when merged

### CODE REVIEW

**Comment by KBOE2** [comment]
For admin/dev contact you can use developer[at]lss-manager.de

**Comment by KokosnussDEV** [comment]
Do we want to add a 2nd email to contact if the report is about a team member?

**Comment by KokosnussDEV** [comment]
@LSS-Manager/developers please review

**Review by Ron31 — APPROVED** [review]

**Review by KBOE2 — APPROVED** [review]

**Review by Tsumiki-Chan — APPROVED** [review]
Lgtm

**Pull request merged**
