### PR TITLE
🔀💄 [dashboard] add maxMissions to summary

### PR DESCRIPTION
**Pull request by Cr4zyc4k3**
**What kind of update does this PR provide?** *Please check*

- [ ] new translations / updated translations / translation fixes
- [ ] a new feature
- [ ] a new module
- [ ] a bugfix for an existing feature / module
- [x] improvement of style or user experience
- [ ] other: *Please fill out*

**What is included in your update?**
* adds maxMission as value to the dashboard summary should close one of the two missing points on #12

### CODE REVIEW

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Review by deoxis9001 — CHANGES_REQUESTED** [review]
`        "maxMissions": { "title": "Missions maximum" },`
fr_FR

**Review by jxn-30 — APPROVED** [review]

**Pull request merged**
