### PR TITLE
🔀[dev] add pre-commit package

### PR DESCRIPTION
**Pull request by Cr4zyc4k3**
**What kind of update does this PR provide?** *Please check*

- [ ] new translations / updated translations / translation fixes
- [ ] a new feature
- [ ] a new module
- [ ] a bugfix for an existing feature / module
- [ ] improvement of style or user experience
- [X] other: Improvement of dev experience

**What is included in your update?**
* Add package [pre-commit](https://www.npmjs.com/package/pre-commit) to do linting and styling before commiting

**Additional notes**
[`--no-verify`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---no-verify) can bypass this feature

### CODE REVIEW

**Comment by jxn-30** [comment]
does this work with yarn?

I always get a 
```
pre-commit: Failed to locate the `npm` binary, make sure it's installed in your $PATH.
```

but I didn't find on https://github.com/observing/pre-commit if there's a way to tell pre-commit to use yarn.

**Comment by kdev** [comment]
Why not use husky?

**Comment by jxn-30** [comment]
@Cr4zyc4k3 I have replaced [pre-commit](https://www.npmjs.com/package/pre-commit) with [husky](https://typicode.github.io/husky/) as it is still maintained and causes fewer issues with yarn.
Does this still fullfill your intention of the change?

**Review by kdev — APPROVED** [review]

**Comment by Cr4zyc4k3** [comment]
@jxn-30 I'm not the biggest fan of the husky syntax but since it does the job I'm fine with it.

**Pull request merged**
