### PR TITLE
🐛 [missionHelper] Fix patient_additional not always on top

### PR DESCRIPTION
**Pull request by JRH-1997**

### CODE REVIEW

**Comment by JRH-1997** [comment]
Added a fix for the dashboard.  This will translate the "Back"-button of the sunburst chart.

**Comment by JRH-1997** [comment]
And added another fix for dashboard. Now it calculates the totals form the data of the vehicle API.

**Review by jxn-30 — APPROVED** [review]
Jo, könnet mer so mache glaub i

**Comment by JRH-1997** [comment]
@jxn-30  Waarom ga je Duits naar mij schrijven 😜

**Comment by jxn-30** [comment]
Weil my englisch war ein little bit broke

**Comment by JRH-1997** [comment]
😂

**Pull request merged**
