### PR TITLE
🔀🌐 [fr_FR] Update of 2 missing extensions

### PR DESCRIPTION
**Pull request by deoxis9001**
**What kind of update does this PR provide?** *Please check*

- [x] new translations / updated translations / translation fixes
- [x] a new feature
- [ ] a new module
- [ ] a bugfix for an existing feature / module
- [ ] improvement of style or user experience
- [ ] other: *Please fill out*

**Which language(s) did you add/update translations for?**
*use the xx_XX notation for exact language!*
* fr_FR

**What is included in your update?**
* Add extension Aeroport
* Add extension pump
* adjust the personnel of the vehicles

**Additional notes**
Please add any further notes here!

### CODE REVIEW

**Comment by deoxis9001** [comment]
Is it possible to generate a build?

**Review by Cr4zyc4k3 — APPROVED** [review]

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Comment by deoxis9001** [comment]
I don't understand why it doesn't work

**Comment by deoxis9001** [comment]
I corrected the problem
you have to regenerate a build?

**Comment by Cr4zyc4k3** [comment]
No, the build runs on every commit. If the build is successful I will trigger the deployment.

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Comment by Cr4zyc4k3** [comment]
@deoxis9001 Build online

**Comment by deoxis9001** [comment]
Can you start the deployment again?

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Comment by deoxis9001** [comment]
it's all good for me
you can merge

**Pull request merged**
