### PR TITLE
🔀🌐 [fr_FR] Correction of U.I.I.S.C building position

### PR DESCRIPTION
**Pull request by deoxis9001**
**What kind of update does this PR provide?** *Please check*

- [ ] new translations / updated translations / translation fixes
- [ ] a new feature
- [ ] a new module
- [ ] a bugfix for an existing feature / module
- [x] improvement of style or user experience
- [ ] other: *Please fill out*

**Which language(s) did you add/update translations for?**
*use the xx_XX notation for exact language!*
* xx_XX
* yy_YY
* ...

**What is included in your update?**
* correction of U.I.I.S.C building position

**Additional notes**
Please add any further notes here!

### CODE REVIEW

**Comment by deoxis9001** [comment]
where to find in-game colors

**Comment by jxn-30** [comment]
The colors are self-chosen and can only be found in dashboard afterwards.

**Comment by jxn-30** [comment]
Is this ready to merge?

**Comment by Cr4zyc4k3** [comment]
@deoxis9001 status?

**Comment by deoxis9001** [comment]
> Is this ready to merge?

yes sorry^_^

**Review by jxn-30 — APPROVED** [review]

**Pull request merged**
