### PR TITLE
🔀✨ [dashboard] add police cells to overview

### PR DESCRIPTION
**Pull request by Cr4zyc4k3**
**What kind of update does this PR provide?** *Please check*

- [ ] new translations / updated translations / translation fixes
- [x] a new feature
- [ ] a new module
- [ ] a bugfix for an existing feature / module
- [ ] improvement of style or user experience
- [ ] other: *Please fill out*

**What is included in your update?**
* Add cells to the dashboard building overview

### CODE REVIEW

**Comment by Cr4zyc4k3** [comment]
@lss-manager deploy

**Comment by Cr4zyc4k3** [comment]
@lss-manager deploy

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Comment by deoxis9001** [comment]
```
        "cells": "Cellules",
        "cellsFree": "Cellules libre",
```
fr_FR

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Comment by Cr4zyc4k3** [comment]
Since neither @jxn-30 nor me can figure out why the cells won't counted porperly I'll close this issue atm.

**Pull request closed without merging**
