### PR TITLE
🔀🌐[fr_FR] Fix School and building and Update DOCS

### PR DESCRIPTION
**Pull request by deoxis9001**
**What kind of update does this PR provide?** *Please check*

- [x] new translations / updated translations / translation fixes
- [ ] a new feature
- [ ] a new module
- [x] a bugfix for an existing feature / module
- [ ] improvement of style or user experience
- [ ] other: *Please fill out*

**Which language(s) did you add/update translations for?**
*use the xx_XX notation for exact language!*
* fr_FR

**What is included in your update?**
* Fix School and building
* Update docs

**Additional notes**

### CODE REVIEW

**Comment by deoxis9001** [comment]
@LSS-Manager deploy

**Comment by jxn-30** [comment]
@LSS-Manager deploy

**Comment by Cr4zyc4k3** [comment]
iirc the docs are build from the latest beta to have at least some stability

**Review by Cr4zyc4k3 — APPROVED** [review]

**Comment by Cr4zyc4k3** [comment]
Please mention if this PR is ready to get merged

**Comment by Cr4zyc4k3** [comment]
LGTM

**Pull request merged**
