### PR TITLE
Update en_GB.json

### PR DESCRIPTION
**Pull request by Gooochy**
Changed some writing to fit the UK

### CODE REVIEW

**Comment by kdev** [comment]
I think it would be best to have another translator look over this? I don't know if everyone prefers the changes or not.

**Comment by Gooochy** [comment]
> I think it would be best to have another translator look over this? I don't know if everyone prefers the changes or not.
> (btw I think we have to change the target branch to dev? @jxn-30)

Should I change it to fire pump?

**Comment by kdev** [comment]
> 
> 
> > I think it would be best to have another translator look over this? I don't know if everyone prefers the changes or not.
> > (btw I think we have to change the target branch to dev? @jxn-30)
> 
> Should I change it to fire pump?

Thats the problem, I'm not a native so I cannot really say how people say it in the UK

**Comment by Gooochy** [comment]
> > > I think it would be best to have another translator look over this? I don't know if everyone prefers the changes or not.
> > > (btw I think we have to change the target branch to dev? @jxn-30)
> > 
> > 
> > Should I change it to fire pump?
> 
> Thats the problem, I'm not a native so I cannot really say how people say it in the UK

Pump is the generic term but every Fire service is different form pump Ladder-water Ladder-dual purpose ladder

**Comment by jxn-30** [comment]
As long as no one complains, this shall be fine altough in the "Requirements for this mission" info other wordings are used.

@Gooochy FYI: Please always remember to use `dev` as target branch for pullRequests and also do the file editings always on `dev`-branch ;)

**Pull request merged**
