### PR TITLE
🔀Mission Helper Update

### PR DESCRIPTION
**Pull request by deoxis9001**
**What kind of update does this PR provide?** *Please check*

- [x] new translations / updated translations / translation fixes
- [ ] a new feature
- [ ] a new module
- [ ] a bugfix for an existing feature / module
- [x] improvement of style or user experience
- [ ] other: *Please fill out*

**Which language(s) did you add/update translations for?**
*use the xx_XX notation for exact language!*
* fr_FR

**What is included in your update?**
* Hide the title of the vehicles if no vehicle
* [fr_FR]  Update Translation specialization 
* [fr_FR]  Update "height_rescue_personnel" not badge
* Add Title for Special requirements

**Additional notes**
Please add any further notes here!
I'm not sure about the title "Special requirements".
Is it possible to have a preview?

### CODE REVIEW

**Comment by jxn-30** [comment]
@LSS-Manager deploy

**Comment by deoxis9001** [comment]
How to make the word vehicles disappear on missions ?
2022-11-06 11_48_16-missions_129999434 _ Operateur112 fr

**Comment by deoxis9001** [comment]
Is it possible to have a new preview?

**Comment by jxn-30** [comment]
@LSS-Manager deploy

**Comment by deoxis9001** [comment]
I tested several things and I can't make the vehicle title disappear if he doesn't have a vehicle

**Comment by jxn-30** [comment]
I will have a look at it later this day.

**Comment by jxn-30** [comment]
@LSS-Manager deploy

**Comment by jxn-30** [comment]
@deoxis9001 please review if it now matches your ideas :)

**Comment by deoxis9001** [comment]
it's all good :)

**Review by jxn-30 — APPROVED** [review]

**Pull request merged**
