### PR TITLE
✨ dispatchcenter-view update and fixes

### PR DESCRIPTION
**Pull request by JRH-1997**
@jxn-30 I need a German translation for "Add buildings:" as header above the buildingselection. 
And maybe you could find a solution for the remove board. After removing it's not showing any board.  Otherwise I can live with that.

### CODE REVIEW

**Comment by jxn-30** [comment]
Translation: `Gebäude hinzufügen`
For the board, I will have a look myself before merging if I do remember by then

**Review by jxn-30 — APPROVED** [review]
i hope you guys do know what you are doing :)

**Comment by JRH-1997** [comment]
> i hope you guys do know what you are doing :)
No I don't but I did something and it was a table 😂

**Comment by jxn-30** [comment]
> > i hope you guys do know what you are doing :)
> > No I don't but I did something and it was a table joy

That sounds as if you're working the same way, I do :+1:

**Pull request merged**
