### PR TITLE
🔀Hotkeys

### PR DESCRIPTION
**Pull request by Cr4zyc4k3**
**What kind of update does this PR provide?** *Please check*

- [ ] new translations / updated translations / translation fixes
- [X] a new feature
- [ ] a new module
- [ ] a bugfix for an existing feature / module
- [ ] improvement of style or user experience
- [ ] other: *Please fill out*

**What is included in your update?**
* Hotkeys for vehicles, see #15

### CODE REVIEW

**Comment by jxn-30** [comment]
@LSS-Manager deploy

**Comment by jxn-30** [comment]
@LSS-Manager deploy

**Review by deoxis9001 — CHANGES_REQUESTED** [review]
```
        "vehicles": {
            "alarm": {
                "firstAllianceMission": "Signal d'alarme pour la première mission de l'alliance",
                "firstOwnMission": "Signal d'alarme pour la première mission personnel",
                "title": "alarmE"
            },
            "goto": {
                "building": "bâtiments",
                "edit": "edit",
                "nextVehicle": "véhicule suivant",
                "personalAssigment": "affectation du personnelle",
                "previousVehicle": "véhicule Précédent",
                "statistics": "stats",
                "title": "allez"
            },
            "other": {
                "moveVehicle": "déplacer le véhicule",
                "title": "etc.",
                "toggleFMS": "changer le statut"
            },
            "title": "véhicules"
        }
```
fr_FR

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Comment by Cr4zyc4k3** [comment]
@LSS-Manager deploy

**Comment by jxn-30** [comment]
@LSS-Manager deploy

**Comment by jxn-30** [comment]
@Cr4zyc4k3 Redesign compatibility should work now. I tested it a lot but it would be very good if you tested it too, just to be sure :wink:

**Comment by Cr4zyc4k3** [comment]
> @Cr4zyc4k3 Redesign compatibility should work now. I tested it a lot but it would be very good if you tested it too, just to be sure wink

Wörks like a charm :blush:

**Review by jxn-30 — APPROVED** [review]

**Pull request merged**
