### PR TITLE
🎉[eb] Feature request implementation

### PR DESCRIPTION
**Pull request by Suchty112**
**What kind of update does this PR provide?** *Please check*

- [ ] new translations / updated translations / translation fixes
- [ ] a new feature
- [ ] a new module
- [ ] a bugfix for an existing feature / module
- [x] improvement of style or user experience
- [ ] other: *Please fill out*

**Which language(s) did you add/update translations for?**
*use the xx_XX notation for exact language!*
* all

**What is included in your update?**
* Feature request implementation from #2430 

**Additional notes**
Please add any further notes here!

### CODE REVIEW

**Comment by Suchty112** [comment]
@LSS-Manager-Bot deploy

**Comment by Suchty112** [comment]
@LSS-Manager deploy

**Comment by Cr4zyc4k3** [comment]
maybe use `label-warning` or `label-info` due to better visibility in the dark mode?

**Review by Cr4zyc4k3 — APPROVED** [review]

**Comment by Suchty112** [comment]
@LSS-Manager deploy

**Comment by Suchty112** [comment]
@LSS-Manager deploy

**Pull request merged**
