### PR TITLE
🔀 🐛 [hotkeys] fix #1812 uniqueness check

### LINKED ISSUE #1812: [BUG]: false positive uniqueness check in hotkeys setting due to special requirements
### What happened?

LSSM does not allow users to assign the same hotkey to multiple actions, although they aren't executed in the same browser context

### How to reproduce?

1. Enable `hotkeys` module
2. in settings, set a hotkey for an action in the mission window
3. try to set a hotkey for an action on the main window with the same hotkey as above. LSSM will not allow to do so (see Screenshot):
grafik

### Expected behavior

LSSM should allow setting the same hotkey for multiple actions, if they don't overlap.

### System

- OS: *any*
- Browser and version: *any*
- LSSM-Version: latest (4.6.2)
- Game-Version: *any*

### Additional

The first scope of an action name identifies the location (`window.location`) where an action can be executed. The same hotkey may not be set on multiple actions sharing this part of the scope.
Cave: `*` identifies "all locations"

### PR DESCRIPTION
**Pull request by jxn-30**
**What kind of update does this PR provide?** *Please check*

- [ ] new translations / updated translations / translation fixes
- [ ] a new feature
- [ ] a new module
- [x] a bugfix for an existing feature / module
- [ ] improvement of style or user experience
- [ ] other: *Please fill out*

**What is included in your update?**
* A bugfix that will close #1812 

**Additional notes**
`unique` attribute on appendableList items are now allowed to be functions.

### CODE REVIEW

**Comment by jxn-30** [comment]
@LSS-Manager deploy

@Suchty112 , @Cr4zyc4k3 please test this when reviewing, I got a feeling that there is an edgecase that doesn't work yet.

**Comment by jxn-30** [comment]
@LSS-Manager deploy

**Review by Cr4zyc4k3 — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/69073372/198054557-179d5c62-e7d1-45c9-8e9e-cabda354da3e.mp4

As seen here, there are some issues with existing hotkeys.

**Comment by jxn-30** [comment]
@LSS-Manager deploy

**Comment by jxn-30** [comment]
> hotkeysUnique-2022-10-26_16.22.08.mp4
> 
> As seen here, there are some issues with existing hotkeys.

Should be fixed with 4f3a535 but please test again once the preview-build has been deployed.

**Review by Cr4zyc4k3 — APPROVED** [review]

**Pull request merged**
