### PR TITLE
✨➕🔨 [docs/dev] hot reloading

### PR DESCRIPTION
**Pull request by Cr4zyc4k3**
**What kind of update does this PR provide?** *Please check*

- [ ] new translations / updated translations / translation fixes
- [ ] a new feature
- [ ] a new module
- [ ] a bugfix for an existing feature / module
- [x] improvement of style or user experience
- [ ] other: *Please fill out*

**What is included in your update?**
* New flag `--local` for the build.sh
* New dev dependency for testing on localhost
   * add hot reloading
* Some documentation

**Additional notes**
Please add any further notes here!

### CODE REVIEW

**Comment by jxn-30** [comment]
let's allow setting a port via argument when using the local build. (Standard e.g. 3000 if the argument is not given).

We could then  do some sneaky adjustments:
* src/config.ts => automatically do localhost:{port} as server if a special env variable is set
* use the port for creating the local userscript
* use the port for starting the live-server

anything I missed? An Edge-Case that could cause problems when implementing this?

**Comment by Cr4zyc4k3** [comment]
I'm not quite sure whether this works with [::1] (Ipv6), but lets try :D

**Comment by jxn-30** [comment]
> let's allow setting a port via argument when using the local build. (Standard e.g. 3000 if the argument is not given).
> 
> We could then do some sneaky adjustments:
> 
>     * src/config.ts => automatically do localhost:{port} as server if a special env variable is set
> 
>     * use the port for creating the local userscript
> 
>     * use the port for starting the live-server
> 
> 
> anything I missed? An Edge-Case that could cause problems when implementing this?

@Cr4zyc4k3 that one is now added. I think, the docs need to be updated accordingly and we should test that thingy in case I missed anything.

**Comment by Cr4zyc4k3** [comment]
`./build/build.sh --local` currently crashes with
```bash
### [👷] webpack ###
Let's build that stuff! version: 4.7.8+20230828.1111; branch: feat-testLocal;
Generated configurations. Building…
Error: ENOENT: no such file or directory, open './dist/static/fileSizes.json'
    at Object.openSync (node:fs:589:3)
    at Object.writeFileSync (node:fs:2247:35)
    at /home/arne/WebstormProjects/LSSM-V.4/build/index.ts:131:12
    at /home/arne/WebstormProjects/LSSM-V.4/node_modules/webpack/lib/webpack.js:157:8
    at /home/arne/WebstormProjects/LSSM-V.4/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/home/arne/WebstormProjects/LSSM-V.4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/arne/WebstormProjects/LSSM-V.4/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/home/arne/WebstormProjects/LSSM-V.4/node_modules/webpack/lib/Cache.js:150:23)
    at /home/arne/WebstormProjects/LSSM-V.4/node_modules/webpack/lib/Compiler.js:1229:15
    at Hook.eval [as callAsync] (eval at create (/home/arne/WebstormProjects/LSSM-V.4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './dist/static/fileSizes.json'
}
```

**Comment by Cr4zyc4k3** [comment]
And for some reason the command will build `lssm-v4.user.js`  and the `lssm-v4.local.user.js` but both have the local server as source, which defeats the reason for a local script.

Proposal: `.user.js` will always refer to the given url from config.ts.

**Comment by jxn-30** [comment]
> `./build/build.sh --local` currently crashes with
> 
> ```shell
> ### [👷] webpack ###
> Let's build that stuff! version: 4.7.8+20230828.1111; branch: feat-testLocal;
> Generated configurations. Building…
> Error: ENOENT: no such file or directory, open './dist/static/fileSizes.json'
>     at Object.openSync (node:fs:589:3)
>     at Object.writeFileSync (node:fs:2247:35)
>     at /home/user/WebstormProjects/LSSM-V.4/build/index.ts:131:12
>     at /home/user/WebstormProjects/LSSM-V.4/node_modules/webpack/lib/webpack.js:157:8
>     at /home/user/WebstormProjects/LSSM-V.4/node_modules/webpack/lib/HookWebpackError.js:68:3
>     at Hook.eval [as callAsync] (eval at create (/home/user/WebstormProjects/LSSM-V.4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
>     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/user/WebstormProjects/LSSM-V.4/node_modules/tapable/lib/Hook.js:18:14)
>     at Cache.shutdown (/home/user/WebstormProjects/LSSM-V.4/node_modules/webpack/lib/Cache.js:150:23)
>     at /home/user/WebstormProjects/LSSM-V.4/node_modules/webpack/lib/Compiler.js:1229:15
>     at Hook.eval [as callAsync] (eval at create (/home/user/WebstormProjects/LSSM-V.4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1) {
>   errno: -2,
>   syscall: 'open',
>   code: 'ENOENT',
>   path: './dist/static/fileSizes.json'
> }
> ```

that one is fixed by 0913243 

---

> And for some reason the command will build `lssm-v4.user.js`  and the `lssm-v4.local.user.js` but both have the local server as source, which defeats the reason for a local script.
> 
> Proposal: `.user.js` will always refer to the given url from config.ts.

I kinda intended this to make things easier, we would have to have some more extensive / complicated config to split them up. Maybe I'm overseeing something.
Also I don't think, that this is a greater issue.

**Comment by Cr4zyc4k3** [comment]
Now works on my machine as well. LGTM?

**Comment by Cr4zyc4k3** [comment]
LGTM, again :D

**Comment by deoxis9001** [comment]
I use windows so I can't run it locally?

**Comment by deoxis9001** [comment]
image
userscript is not available

**Comment by Cr4zyc4k3** [comment]
> I use windows so I can't run it locally?

No, unfortunaly the scripts currently only work on unix like systems. As a workaround we recommand WSL.



> image userscript is not available

Thats odd, because there should be a least the default shipped userscript 

> add the listening url to build.sh example: build/build.sh --local --port 1234 --url 88.88.88.88

Can you provide a scenario where you need to specify an ip instead of localhost or 0.0.0.0? Currently I see no reason where the ip is relevant.

**Comment by Cr4zyc4k3** [comment]
I had a quick talk with the other devs: We understand the reason, but this diverges from the original intention to start a local instance to check out your changes. We recommend WSL or the  git bash if you use a windows system. And we plan to port the build script to windows, see #2598

**Review by jxn-30 — APPROVED** [review]

**Comment by deoxis9001** [comment]
which would be cool,
is that once you update a file like MissionHelper/fr_FR.root.json
it reloads the missionHelper module directly

**Comment by Cr4zyc4k3** [comment]
So, you want hot reloading? I'll have a look, but I think the easiest way is to bind "rebuild the dist" on the save key (ctrl +s) in your IDE

**Comment by Cr4zyc4k3** [comment]
Nvm, sounds like we could implement this with webpack: https://webpack.js.org/guides/development/ but I dont have time to work on it till next week.

**Comment by Cr4zyc4k3** [comment]
Close in favor of  #2852

**Pull request closed without merging**
